### PR TITLE
Feature/marketing site content

### PR DESCRIPTION
**Pull request by DistractionBoy**
This still needs Korean translation but I wanted to push an initial draft, since the L2Dao is no longer involved with the project and helping with securing funding.

### CODE REVIEW

**Comment by anhfactor** [comment]
need to translate some vietnamese text in funding page

**Comment by DistractionBoy** [comment]
i'm going to create the json additions needed for the translations, now that the content is somewhat finalized. the proposal will change, and we'll update this page in the site along with it, but this is a decent starting point.

**Comment by anhfactor** [comment]
> i'm going to create the json additions needed for the translations, now that the content is somewhat finalized. the proposal will change, and we'll update this page in the site along with it, but this is a decent starting point.

okay sure, will wait for you, i have completed vietnamese translation

**Comment by anhfactor** [comment]
Got error when build in "./components/Proposals/ProposalL2.tsx" because commonLang dont have key, value (background, background_desc1, ... etc) you need to add it in "./lang/common.json" 
image

**Comment by anhfactor** [comment]
It works !!! You can merge it.

**Review by anhfactor — APPROVED** [review]
It works!, @jason-pierce-designs you can merge it.

**Pull request merged**
