### PR TITLE
Top menu feature

### PR DESCRIPTION
**Pull request by anhfactor**
- Chain, language, dark/light mode ✅
* Continue working on dark/light mode & language function

### CODE REVIEW

**Comment by DistractionBoy** [comment]
Thank you so much for being our first contributor! I look forward to all your contributions and really, from the bottom of my heart, am so glad to have your help.

I would like to ask for a few changes:

1) Could you remove the button for changing the network? This marketing site will be web3 capable for a few reasons, but right now we haven't integrated a wallet connect api so the button to change network doesn't really have any use... yet (but soon it will)
2) Could you change the first other language supported to Vietnamese? Since you're a native speaker, I think that makes sense. We can start to build out the Vietnamese translations right away. It's better to have complete, stable features added in an incremental fashion, and right now we don't have a Thai native speaking contributor. When we do, we will add it as a supported language

**Comment by DistractionBoy** [comment]
oh one more thing i almost forgot. for your next PR, could we combine the light/dark mode and language settings into a User Menu kind of dropdown? We can change the text from "Soon" to "Menu" for now, and then later when we add wallet connect add an avatar style menu button that makes the user menu visible and has all the options in it.

**Review by DistractionBoy — CHANGES_REQUESTED** [review]
just a few minor changes, listed in the Overview section

**Comment by anhfactor** [comment]
That supers, i agree with your idea. Let me change it and let you know.

**Review by westonnelson — APPROVED** [review]

**Review by DistractionBoy — APPROVED** [review]
Look Good To Me!

**Pull request merged**
